CREATE USER demo1_user WITH PASSWORD 'demo1_pass';
CREATE DATABASE demo1_db WITH OWNER demo1_user;
GRANT ALL PRIVILEGES ON DATABASE demo1_db TO demo1_user;
GRANT ALL PRIVILEGES ON SCHEMA public TO demo1_user;
ALTER DEFAULT PRIVILEGES FOR ROLE demo1_user IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO demo1_user;
